# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HS3HMnGoKS_5YFKcWkh0mgwIC1Mbo15b
"""

import re
import requests
from bs4 import BeautifulSoup as bs
import pandas as pd

from urllib.parse import urljoin

books=[]

base_url='https://books.toscrape.com/'
url=base_url
while url:
  req=requests.get(url)
  soup=bs(req.text,'html.parser')
  articles=soup.find_all('article',class_='product_pod')
  for article in articles:
    image_url=article.find('img').get('src')
    rating=article.find('p').get('class')
    title=article.find('h3').find('a').get('title')
    price=article.find('p',class_='price_color').text.strip().replace('Â£','')
    instock=article.find('p',class_='instock availability').text.strip()
    book_url=article.find('h3').find('a').get('href')

    books.append({
      'image_url':urljoin(url,image_url),
      'rating':rating[1],
      'title':title,
      'price':float(price),
      'instock':instock,
      'book_url':urljoin(url,book_url)
    })
  next_url=soup.find('a',string='next')
  if next_url:
    url=urljoin(url,next_url.get('href'))
  else:
    url=None


df=pd.DataFrame(books)
df.head(5)
print(df.info())

df.to_csv('books.csv',index=False)